name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v2.1.5
      #- name: Check node version
      #  run: node -v
      # - uses: ./action-a
      #  with:
      #    MY_NAME: "Mona"
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: | 
          mvn -v
          python --version
      - uses: actions/checkout@v1
      - run: |
          git pack-refs --all
          python gitVersionCalculator/calculateSemVersion.py > semver.txt
      - run: echo -n -e "HELLO\n !\n WWWorld!" > version.txt
      - uses: pCYSl5EDgo/cat@master
        id: semver
        with:
          path: version.txt
      - run: echo $TEXT
        env:
          TEXT: ${{ steps.semver.outputs.text }}
      - name: Compile
        run: make -s compile #mvn -q clean compile -DskipTests
